#**Pandas**
Powerful and flexible open-source data analysis and manipulation tool

Using **Student_Dataset** for this task

In [1]:
import pandas as pd

#Load dataset

In [2]:
df = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/IDRA/Day7_Student_Dataset.csv")
df = pd.DataFrame(df)

#Inspecting first & last rows

In [3]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [4]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

#View random sample

In [5]:
df.sample(n=5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi

#Info about the dataset

In [6]:
print("Dataset shape = ", df.shape)
print("\nIndex = ", df.index)
print("\nColumns = ", df.columns)
print("\nData types =\n",df.dtypes)

Dataset shape =  (25, 7)

Index =  RangeIndex(start=0, stop=25, step=1)

Columns =  Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

Data types =
 Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

We can see that
- there are 25 rows
- there are 7 columns with:
  - Student_ID and Age having int values
  - Marks and Attendance_Percentage having float values
  - Name, Course and City having object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

From checking the info, we can see
- there are 25 rows and 7 columns
- there are one null value in Marks, Attendance_Percentage and City columns each
- the memory used by this DataFrame

In [8]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

We can see from the describe that the average age of the students in this dataset is 20, with minimum being 18 and maximum being 23

#Missing values

In [9]:
df.isna().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [10]:
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

.isna() and .isnull() gives the same output
- **isna()** is the primary function
- **isnull()** is alias for isna()

#**Recap**
- read_csv function for loading the dataset in .csv format
- head() to show the first 5 rows
- tail() to show the last 5 rows
- sample() with no_of_rows argument to show random rows
- .shape gives the no. of rows and columns
- .columns gives the name of the columns in the DataFrame
- .index gives the indices of the DataFrame
- .dtype gives the datatype of each column in the DataFrame
- .info() gives the overall structure of the DataFrame
- .describe() gives the descriptive statistics of the DataFrame
- isna() and isnull() checks if there are any missing values in each column